# HTML report generation ----------------------------------------------------

#' Write a self-contained HTML reconciliation report
#'
#' Produce an HTML file summarising a [reconciliation] object: provenance
#' metadata, match-type breakdown, full mapping table, and a list of
#' unresolved / flagged species. The file has no external dependencies
#' (CSS is inlined), so it is suitable for sharing with collaborators,
#' pasting into supplementary materials, or archiving next to analysis
#' outputs.
#'
#' \if{html}{\figure{reconcile-report-top.png}{options: width=700 alt="Top of the reconciliation report: run header, coverage summary, and match-composition chart."}}
#'
#' @section Layout:
#' The report opens with a run header (the originating
#' `reconcile_tree()` / `reconcile_data()` call, timestamp, package
#' version), the match-coverage summary, and a compact bar chart of
#' match composition. Below those, per-match-type detail tables
#' (normalised, synonym, fuzzy, flagged) and the unresolved-species
#' list make each decision auditable. The `bird-workflow` vignette
#' includes annotated screenshots of both sections.
#'
#' @param reconciliation A [reconciliation] object returned by
#'   [reconcile_tree()], [reconcile_data()], or a related matcher.
#' @param file A length-1 character vector. Output file path. Must end in `.html`.
#' @param title A length-1 character vector. Report title shown at the top of the
#'   page. Default is generic.
#' @param open Logical. Open the finished report in the default
#'   browser? Defaults to `TRUE` in interactive sessions, `FALSE`
#'   otherwise (so it does not block scripts).
#'
#' @return The file path, invisibly.
#'
#' @family reconciliation functions
#' @seealso [reconcile_summary()] for a console equivalent;
#'   [reconcile_export()] to additionally save aligned data and tree
#'   files.
#'
#' @examples
#' data(avonet_subset)
#' data(tree_jetz)
#' rec <- reconcile_tree(avonet_subset, tree_jetz,
#'                       x_species = "Species1", authority = NULL)
#' f <- tempfile(fileext = ".html")
#' reconcile_report(rec, file = f, open = FALSE)
#' cat("Report written to:", f, "\n")
#'
#' @export
reconcile_report <- function(reconciliation,
                              file,
                              title = "Reconciliation Report",
                              open = interactive()) {

  validate_reconciliation(reconciliation)

  if (!grepl("[.]html$", file, ignore.case = TRUE)) {
    abort("`file` must end in '.html'.", call = caller_env())
  }

  mapping <- reconciliation$mapping
  meta    <- reconciliation$meta
  counts  <- reconciliation$counts

  # --- Build sub-tables ---
  matched     <- mapping[mapping$in_x & mapping$in_y, ]
  exact_m     <- mapping[mapping$match_type == "exact", ]
  norm_m      <- mapping[mapping$match_type == "normalized", ]
  syn_m       <- mapping[mapping$match_type == "synonym", ]
  fuzzy_m     <- mapping[mapping$match_type == "fuzzy", ]
  manual_m    <- mapping[mapping$match_type == "manual", ]
  flagged_m   <- mapping[mapping$match_type == "flagged", ]
  unres_x     <- mapping[mapping$match_type == "unresolved" &
                           mapping$in_x & !mapping$in_y, ]
  unres_y     <- mapping[mapping$match_type == "unresolved" &
                           !mapping$in_x & mapping$in_y, ]

  # --- Assemble HTML ---
  html <- character()
  add <- function(...) html <<- c(html, paste0(...))

  add("<!DOCTYPE html>")
  add("<html lang='en'><head><meta charset='utf-8'>")
  add("<title>", pr_html_escape(title), "</title>")
  add("<style>")
  add(pr_report_css())
  add("</style></head><body>")

  # Header
  add("<h1>", pr_html_escape(title), "</h1>")
  add("<div class='meta'>")
  add("<p><strong>Generated by</strong> prepR4pcm ",
      meta$prepR4pcm_version %||% "", " &mdash; ",
      format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "</p>")

  type_label <- switch(
    meta$type,
    data_data = "data vs data",
    data_tree = "data vs tree",
    tree_tree = "tree vs tree",
    multi     = "multiple datasets vs tree",
    meta$type
  )

  add("<table class='meta-table'>")
  add("<tr><td>Type</td><td>", type_label, "</td></tr>")
  add("<tr><td>Source x</td><td>", pr_html_escape(meta$x_source), "</td></tr>")
  add("<tr><td>Source y</td><td>", pr_html_escape(meta$y_source), "</td></tr>")
  add("<tr><td>Authority</td><td>", meta$authority %||% "none", "</td></tr>")
  add("<tr><td>Reconciliation date</td><td>",
      format(meta$timestamp, "%Y-%m-%d %H:%M:%S"), "</td></tr>")
  add("</table></div>")

  # Summary counts
  add("<h2>Match summary</h2>")
  n_total <- counts$n_x
  pct <- function(n) if (n_total == 0) "" else sprintf("%.1f%%", 100 * n / n_total)

  add("<table class='summary'>")
  add("<tr><th>Match type</th><th>Count</th><th>% of x</th></tr>")
  rows <- list(
    c("Exact",      counts$n_exact),
    c("Normalized", counts$n_normalized),
    c("Synonym",    counts$n_synonym),
    c("Fuzzy",      counts$n_fuzzy),
    c("Manual",     counts$n_manual),
    c("Flagged",    counts$n_flagged)
  )
  for (r in rows) {
    n <- as.integer(r[2])
    cls <- if (n > 0) "" else " class='zero'"
    add("<tr", cls, "><td>", r[1], "</td><td>", n, "</td><td>", pct(n), "</td></tr>")
  }
  add("<tr class='unresolved'><td>Unresolved (x only)</td><td>",
      counts$n_unresolved_x, "</td><td>", pct(counts$n_unresolved_x), "</td></tr>")
  add("<tr class='unresolved'><td>Unresolved (y only)</td><td>",
      counts$n_unresolved_y, "</td><td></td></tr>")
  add("<tr class='total'><td><strong>Total matched</strong></td><td><strong>",
      nrow(matched), "</strong></td><td><strong>",
      pct(nrow(matched)), "</strong></td></tr>")
  add("</table>")

  # Detail sections
  if (nrow(norm_m) > 0) {
    add("<h2>Normalized matches (", nrow(norm_m), ")</h2>")
    add("<p>Formatting differences resolved automatically.</p>")
    add(pr_mapping_table(norm_m, max_rows = 50))
  }

  if (nrow(syn_m) > 0) {
    add("<h2>Synonym matches (", nrow(syn_m), ")</h2>")
    add("<p>Resolved via taxonomic authority: ", meta$authority %||% "none", ".</p>")
    add(pr_mapping_table(syn_m, max_rows = 50))
  }

  if (nrow(fuzzy_m) > 0) {
    add("<h2>Fuzzy matches (", nrow(fuzzy_m), ")</h2>")
    add("<p>Likely typos detected by string similarity.</p>")
    add(pr_mapping_table(fuzzy_m, max_rows = 50, show_score = TRUE))
  }

  if (nrow(flagged_m) > 0) {
    add("<h2>Flagged for review (", nrow(flagged_m), ")</h2>")
    add("<p>Low-confidence matches requiring manual inspection.</p>")
    add(pr_mapping_table(flagged_m, max_rows = 50, show_score = TRUE))
  }

  if (nrow(manual_m) > 0) {
    add("<h2>Manual overrides (", nrow(manual_m), ")</h2>")
    add(pr_mapping_table(manual_m, max_rows = 50))
  }

  unused_ov <- reconciliation$unused_overrides
  if (!is.null(unused_ov) && nrow(unused_ov) > 0) {
    add("<h2>Unused overrides (", nrow(unused_ov), ")</h2>")
    add("<p>Override rows that could not be applied. Each is tagged ",
        "with a reason code.</p>")
    add("<table>",
        "<thead><tr>",
        "<th>name_x</th><th>name_y</th><th>reason</th>",
        "</tr></thead>",
        "<tbody>")
    show_n <- min(nrow(unused_ov), 50)
    for (i in seq_len(show_n)) {
      add("<tr>",
          "<td>", pr_html_escape(unused_ov$name_x[i]), "</td>",
          "<td>", pr_html_escape(unused_ov$name_y[i]), "</td>",
          "<td><code>", pr_html_escape(unused_ov$reason[i]),
          "</code></td>",
          "</tr>")
    }
    if (nrow(unused_ov) > 50) {
      add("<tr><td colspan='3'><em>... and ",
          nrow(unused_ov) - 50, " more</em></td></tr>")
    }
    add("</tbody></table>")
  }

  if (nrow(unres_x) > 0) {
    add("<h2>Unresolved: in data but not in tree (", nrow(unres_x), ")</h2>")
    add("<ul>")
    show_n <- min(nrow(unres_x), 100)
    for (i in seq_len(show_n)) {
      add("<li>", pr_html_escape(unres_x$name_x[i]), "</li>")
    }
    if (nrow(unres_x) > 100) add("<li><em>... and ", nrow(unres_x) - 100, " more</em></li>")
    add("</ul>")
  }

  if (nrow(unres_y) > 0) {
    add("<h2>Unresolved: in tree but not in data (", nrow(unres_y), ")</h2>")
    add("<ul>")
    show_n <- min(nrow(unres_y), 100)
    for (i in seq_len(show_n)) {
      add("<li>", pr_html_escape(unres_y$name_y[i]), "</li>")
    }
    if (nrow(unres_y) > 100) add("<li><em>... and ", nrow(unres_y) - 100, " more</em></li>")
    add("</ul>")
  }

  add("<hr><p class='footer'>Generated by ",
      "<a href='https://github.com/itchyshin/prepR4pcm'>prepR4pcm</a></p>")
  add("</body></html>")

  # Write file
  dir.create(dirname(file), recursive = TRUE, showWarnings = FALSE)
  writeLines(paste(html, collapse = "\n"), file)
  cli_alert_success("Report written to {.path {file}}")

  if (open) utils::browseURL(file)

  invisible(file)
}


# Internal helpers ---------------------------------------------------------

#' @keywords internal
pr_html_escape <- function(x) {
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x
}

#' @keywords internal
pr_mapping_table <- function(m, max_rows = 50, show_score = FALSE) {
  lines <- character()
  lines <- c(lines, "<table class='detail'>")
  hdr <- "<tr><th>Name (x)</th><th>Name (y)</th>"
  if (show_score) hdr <- paste0(hdr, "<th>Score</th>")
  hdr <- paste0(hdr, "<th>Notes</th></tr>")
  lines <- c(lines, hdr)

  show_n <- min(nrow(m), max_rows)
  for (i in seq_len(show_n)) {
    row <- "<tr>"
    row <- paste0(row, "<td>", pr_html_escape(m$name_x[i] %||% ""), "</td>")
    row <- paste0(row, "<td>", pr_html_escape(m$name_y[i] %||% ""), "</td>")
    if (show_score) {
      score <- if (is.na(m$match_score[i])) "" else sprintf("%.3f", m$match_score[i])
      row <- paste0(row, "<td>", score, "</td>")
    }
    row <- paste0(row, "<td>", pr_html_escape(m$notes[i] %||% ""), "</td>")
    row <- paste0(row, "</tr>")
    lines <- c(lines, row)
  }
  if (nrow(m) > max_rows) {
    cols <- if (show_score) 4 else 3
    lines <- c(lines, sprintf("<tr><td colspan='%d'><em>... and %d more</em></td></tr>",
                               cols, nrow(m) - max_rows))
  }
  lines <- c(lines, "</table>")
  paste(lines, collapse = "\n")
}

#' @keywords internal
pr_report_css <- function() {
  "
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
         sans-serif; max-width: 900px; margin: 2em auto; padding: 0 1em;
         color: #333; line-height: 1.5; }
  h1 { border-bottom: 2px solid #2c3e50; padding-bottom: 0.3em; }
  h2 { color: #2c3e50; margin-top: 1.5em; }
  table { border-collapse: collapse; width: 100%; margin: 1em 0; }
  th, td { text-align: left; padding: 6px 12px; border: 1px solid #ddd; }
  th { background: #f5f5f5; font-weight: 600; }
  .meta { background: #f8f9fa; padding: 1em; border-radius: 6px; margin: 1em 0; }
  .meta-table td:first-child { font-weight: 600; width: 160px; }
  .meta-table { border: none; }
  .meta-table td { border: none; padding: 2px 12px; }
  .summary { max-width: 400px; }
  .summary .zero td { color: #aaa; }
  .summary .unresolved td { color: #c0392b; }
  .summary .total td { border-top: 2px solid #333; }
  .detail { font-size: 0.9em; }
  ul { column-count: 3; column-gap: 2em; }
  li { margin-bottom: 0.2em; }
  .footer { color: #999; font-size: 0.85em; margin-top: 2em; }
  .footer a { color: #999; }
  "
}
